### ISSUE TITLE
The website url (www.openvolunteer.org) in the detalis of this project doesn't provide any valid ssl certficate

### ISSUE THREAD

**Issue by leathersole** [aerogear/OpenVolunteerPlatform#102]
## Bug Report

In the details of project, the website url is www.openvolunteer.org. However, the page doesn't provide any valid ssl certficate.

How to reproduce:

1. click the "www.openvolunteer.org/" link in https://github.com/aerogear/openvolunteerplatform/

Actual result: my browser shows `Warning: Potential Security Risk Ahead`.

**Comment by wtrocki** [comment]
Thank you so much. Website URL is https://OpenVolunteer.org I have changed link

**Comment by leathersole** [comment]
Thanks for fixing it. I close this issue.
