### ISSUE TITLE
Forms documentation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#103]
## Feature Request

Add docs to ionic-forms

**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by wtrocki** [comment]
cc @machi1990

**Comment by machi1990** [comment]
Also /cc @kingsleyzissou would you have some time to take a stab at this?

**Comment by kingsleyzissou** [comment]
Yeah can do, when do we need this by?

So adding a readme to`uniforms-ionic` and then you guys will add it here?

**Comment by wtrocki** [comment]
hmm.. some basic readme will do. We nee just example how to build form. We can copy uniforms docs as well.. Here we can just strap volunteer example etc. :D

**Comment by kingsleyzissou** [comment]
https://github.com/aerogear/uniforms-ionic/pull/10
