### ISSUE TITLE
Create hardcoded admin account for keycloak

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#105]
## Feature Request

We need to hardcode keycloak users to demo data users. Without that it is hard to document simple steps on how to use app

@machi1990 @joaedwar 

**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by machi1990** [comment]
At the moment, 

running `yarn keycloak:init` on the `server` folder will create the `admin:admin` user. Is this what we are looking for here?

**Comment by machi1990** [comment]
> We need to hardcode keycloak users to demo data users. Without that it is hard to document simple steps on how to use app

> At the moment,
> 
> running `yarn keycloak:init` on the `server` folder will create the `admin:admin` user. Is this what we are looking for here?

The init script creates another user i.e `developer:developer` maybe we should change this to `msash:msash`  (Martina Sash) to reflect at least one user we have. WDYT?

**Comment by wtrocki** [comment]
I think admin and developer users might go as we do not have admin user data in db etc. We can nominate one guy to be admin

**Comment by wtrocki** [comment]
Actually ignore me

**Comment by wtrocki** [comment]
Admin cannot be volunteer itself it will be confusing
