### ISSUE TITLE
Use of graphbacks custom client resolvers

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#109]
## Feature Request

We need to implement resolver for custom actions to demo it and also document it properly.

@machi1990 

**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by machi1990** [comment]
This is what we want to achieve for this https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/src/resolvers/custom-resolvers.ts#L9 resolver for example?

**Comment by wtrocki** [comment]
Yep. We need some actions created. The way it could work is that we fetch volunteers that have no actions and recipients with no actions then for each pair we create new action - distribution center pick can be random

**Comment by machi1990** [comment]
Distribution centres can be assigned based on recipient preferred products

**Comment by wtrocki** [comment]
Love it!
