### ISSUE TITLE
Integrate with Graphback 0.14.0 and perform tests

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#147]
## Bug Report

* **Version/Commit**:
* **Ionic Version**:
* **Node.js / npm versions**:

**Comment by machi1990** [comment]
Nice. Renovate picked some of this work in https://github.com/aerogear/OpenVolunteerPlatform/pull/124

**Comment by machi1990** [comment]
Closed by https://github.com/aerogear/OpenVolunteerPlatform/pull/149 and https://github.com/aerogear/OpenVolunteerPlatform/pull/153
