### ISSUE TITLE
Rename Tasks routes and components to actions in client app

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#21]
Quick low hanging fruit to learn how routing and components work together

@machi1990 would that be something easy to do?

**Comment by machi1990** [comment]
Huh this is already done I think - https://github.com/aerogear/OpenVolunteerPlatform/commit/aebc914e5cea3bd32655cf8f22d1ae1b2e6e210a. So let's close this.
