### ISSUE TITLE
Do not use "cache" fetch policy when making GraphQL requests in client-admin app

### ISSUE THREAD

**Issue by machi1990** [aerogear/OpenVolunteerPlatform#39]
The admin app should always retrieve up to date data. 

While doing this issue, we should also:
- remove cache from client config
- remove offix

**Comment by machi1990** [comment]
Taking this one for myself.

**Comment by machi1990** [comment]
So after reading this detailed article by our very own @wtrocki I think we can go with `network-only`. I'll change it a bit later.

**Comment by wtrocki** [comment]
Duplicate of issue where we should remove cache completely
