### ISSUE TITLE
Improve volunteer model and UI components to represent form and other details

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#43]
## Feature Request

- Map component to select an address 
- Validation for people living outside volunteering areas
- Standardize address 
- Add validation for the age (minimal age for volunteer)
- Add working hours from form

<img width="841" alt="Screenshot 2020-04-30 at 15 19 45" src="https://user-images.githubusercontent.com/981838/80721814-94b99680-8af6-11ea-9d9e-6f3ce34e4bfd.png">
:

**Comment by machi1990** [comment]
In Volunteer model we can add how a volunteer wishes to help - more like a skillset.

**Comment by wtrocki** [comment]
I will look into those but makes no sense to have this open
