### ISSUE TITLE
Provide container/docker compose to be able to run platform without compilation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#47]
## Feature Request

Simplify how platform can be used by publishing container to the dockerhub

**Comment by machi1990** [comment]
What should the base image contain? I'd client admin plus server.  Then keycloak + mongodb as backing services.

**Comment by wtrocki** [comment]
Just app server with all clients build - see scripts for building for production.

We already have docker compose for the keycloak and mongo.

**Comment by machi1990** [comment]
> What should the base image contain? I'd client admin plus server. Then keycloak + mongodb as backing services.

Yes, by backing services I meant not part of the platform image.

**Comment by wtrocki** [comment]
See https://github.com/aerogear/datasync-starter/blob/master/scripts/publish_container.sh

**Comment by machi1990** [comment]
Adding here as notes: the [Dockerfile](https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/Dockerfile) could use some updates - compiling the ts file and make sure that only the compiled code is included.
