### ISSUE TITLE
make it easy to contact volunteer 

### ISSUE THREAD

**Issue by machi1990** [aerogear/OpenVolunteerPlatform#60]
simply communication with volunteer (via a chat based system or by optionally adding `phone` details in the volunteer model). The later can be a quick win while with the former  we can put to use subscriptions.

**Comment by wtrocki** [comment]
Good idea, but who will contact volunteer - do you see that being a feature of the recipient app?

**Comment by machi1990** [comment]
For a starter the admin. Sort like `hey, we have this xxx product that needs delivery to xx, are you available?`. Could be extended to the recipient app too - as a means to provide more information about the deliver etc

**Comment by machi1990** [comment]
> While this makes sense we are limited by time and resources so chat seems like nice feature but it might not make it for WIP

Hi @wtrocki yes, indeed this is not the target for MVP. Opened here the idea to keep track of it. Something to re-think post MVP. 

I had this idea when going through the models we current have and noticed that the `Volunteer` model is missing `phone` details - which I think maybe usefully to add to the model at first as a quick win instead of developing chat based based system.
