### ISSUE TITLE
quick link products to volunteer action

### ISSUE THREAD

**Issue by machi1990** [aerogear/OpenVolunteerPlatform#69]
## Feature Request

Idea 1.

<img width="908" alt="Screenshot 2020-05-19 at 13 29 54" src="https://user-images.githubusercontent.com/10106536/82321318-ee660000-99d4-11ea-8a11-d0c30c091151.png">

Maybe on this view we can add a way to create link a product to volunteer action.

**Comment by wtrocki** [comment]
Done
