### ISSUE TITLE
add a possibility to select distribution center location from a map when creating a distribution center

### ISSUE THREAD

**Issue by machi1990** [aerogear/OpenVolunteerPlatform#73]
## Feature Request

By default, the the location should be  the current location, city and address see https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/client-admin/src/pages/CreateDistributionCentrePage.tsx#L31

**Comment by wtrocki** [comment]
Google maps drop marker feature or based on street address?

**Comment by machi1990** [comment]
> Google maps drop marker feature or based on street address?

I'd say by clicking on a map. 

> This sounds hard to me :D

I have not given the complexity a thought about, as I was playing with map component, I thought maybe we can hook an event listener to `onClick` / `onDoubleClick` events, and from there introspect the event - which I hope would contain `latitude` and `longitude`, from the two I think it is very possible using the google map api to find the complete address.

**Comment by wtrocki** [comment]
Yep but map needs to start somewhere so usually people write something to get approx location and then change marker. There are first class handlers for this -  marker dragged events etc. so should not be an issue

**Comment by machi1990** [comment]
> Yep but map needs to start somewhere so usually people write something to get approx location and then change marker. 

Yep, so in the meantime the starting point is current location as can be seen here https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/client-admin/src/pages/CreateDistributionCentrePage.tsx#L23
