### ISSUE TITLE
Use Graphback alpha release

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#74]
## Feature Request
See:
https://github.com/aerogear/graphback/releases/tag/0.14.0-dev2

**Comment by wtrocki** [comment]
CC @machi1990

**Comment by machi1990** [comment]
Good work with the release. @wtrocki @craicoverflow

**Comment by wtrocki** [comment]
0.14.0-dev2 released now

**Comment by machi1990** [comment]
Things to test from top of my head:
- the new runtime (after deletion of resolvers codegen)
- new CRUD capabilities: filtering etc
- RBAC authz  

Can you add to that list? @wtrocki

**Comment by wtrocki** [comment]
That is all!

**Comment by machi1990** [comment]
> * the new runtime (after deletion of resolvers codegen)

Regarding this, do we have sort of a migration guide / wiki ?

**Comment by wtrocki** [comment]
we have - see release notes using graphback master. However runtime is going to change so it is incomplete. You can use mongo template as example

**Comment by machi1990** [comment]
Amazing. I'll start early work on this to kill the codegen'ed resolvers file.

**Comment by machi1990** [comment]
> Amazing. I'll start early work on this to kill the codegen'ed resolvers file.

I have started the work here https://github.com/aerogear/OpenVolunteerPlatform/commit/e24990ef1c2caa1d8c41ae0bffb4888429e9d7c7 and I am current having this error
```
Error: ThunkComposer() returns empty value: undefined
    at ThunkComposer.get ofType [as ofType] (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/ThunkComposer.js:24:13)
    at getTypeNode (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:250:28)
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:323:18
    at Array.map (<anonymous>)
    at getInputValueDefinitionNodes (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:321:21)
    at getInputObjectTypeDefinitionNode (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:55:13)
    at InputTypeComposer.getType (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/InputTypeComposer.js:412:81)
    at NonNullComposer.getType (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/NonNullComposer.js:27:52)
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/ObjectTypeComposer.js:322:23
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/misc.js:134:19
```

**Comment by wtrocki** [comment]
I think that seeing changes really makes me feel that we did not provided nice migration paths in: https://github.com/aerogear/graphback/blob/master/docs/releases.md#migrating-to-0140

Second. I saw this issue for dev1 but I though you have fixed it in dev2.
It might be related to the something we have in schema. 

OVP really pays back as this will be hitting our users if not for OVP

**Comment by machi1990** [comment]
> I think that seeing changes really makes me feel that we did not provided nice migration paths in: https://github.com/aerogear/graphback/blob/master/docs/releases.md#migrating-to-0140
> 
> Second. I saw this issue for dev1 but I though you have fixed it in dev2.
> It might be related to the something we have in schema.

Yes, I thought that too, and reducing the schema to just one business model worked, I thought I could still point it out.
 
> OVP really pays back as this will be hitting our users if not for OVP

Yeap. Good to be able to catch these errors earlier in a real project before the release.

**Comment by wtrocki** [comment]
> Yes, I thought that too, and reducing the schema to just one business model worked, I thought I could still point it out.

In case I will miss that. Create issue in graphback with link to model we will need to experiment to see what is breaking

**Comment by machi1990** [comment]
> > Yes, I thought that too, and reducing the schema to just one business model worked, I thought I could still point it out.
> 
> In case I will miss that. Let's create issue in graphback with link to model we will need to experiment to see what is breaking

Okay, I'll create a graphback's issue linking the model we have in the commit.

**Comment by machi1990** [comment]
Opened https://github.com/aerogear/graphback/issues/1299

**Comment by machi1990** [comment]
> I think that seeing changes really makes me feel that we did not provided nice migration paths in: https://github.com/aerogear/graphback/blob/master/docs/releases.md#migrating-to-0140

Yes, getting back to this, I think we should at lest mention that the gql queries have changed 

mention the usage of filters and page and the ability to retrieve an entity by id with the `getXX` query.
