### ISSUE TITLE
Refine CRUD operations on Volunteer, DistributionCenter and Recipient

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#78]
## Feature Request

- Add some real sample data
- Distribution center - we need them in 40km radius (Pick Paris, NY) 
- Remove stockInformation field
- `Role management` -> `Management`
- Swap icons in product and recipients
- add lat long to recipient
- Remove schedules

**Comment by machi1990** [comment]
> * Remove stockInformation field
> * `Role management` -> `Management`
> * Swap icons in product and recipients
> * add lat long to recipient
> * Remove schedules

https://github.com/aerogear/OpenVolunteerPlatform/pull/81 should address these points

**Comment by machi1990** [comment]
Closed and created https://github.com/aerogear/OpenVolunteerPlatform/issues/91 for adding sample data
