### ISSUE TITLE
Reports view

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#79]
## Feature Request

Create simple reports view with blocks showing numbers.

Possible data to show:

- Number of actions closed today
- A number of actions that were not closed today.
- A number of actions in progress.

**Comment by machi1990** [comment]
Quick thinking about this, make me realise that we'll need to store assignment and completion dates too in the VolunteerAction model. We could start by that and see what kind of filters we'll need by playing with the `/graphql` playground.

**Comment by wtrocki** [comment]
@machi1990 Actually really good point!

**Comment by machi1990** [comment]
> ## Feature Request
> Create simple reports view with blocks showing numbers.
> 
> Possible data to show:
> 
> * Number of actions closed today
> * A number of actions that were not closed today.

The two above, will have to wait for https://github.com/aerogear/graphback/issues/1314.

> * A number of actions in progress.

Yeap. We can add the following:

* Number of actions which are completed.
* Number of actions which are neither assigned nor completed.


We can start with the above three and then to make things fun / challenging, we can also: 
* Number of actions completed nearby the current location (we'll have to define a bounding box or circle). Recipient lat and long could be the determinant location.

**Comment by wtrocki** [comment]
We can move from using Date scalar to string for the moment (timestamp compare will work) and move it back once issue is resolved.

**Comment by machi1990** [comment]
> We can move from using Date scalar to string for the moment (timestamp compare will work) and move it back once issue is resolved.

No need, since the issue if fixed now. I am building the reports queries as we speak and will share them in a moment so that we can add ideas and push our filtering capabilities to the limits :-)

**Comment by machi1990** [comment]
I am current trying the queries out in the graphql playground, some of them are here https://github.com/aerogear/OpenVolunteerPlatform/pull/89
