### ISSUE TITLE
Map view for actions showing recipients as pin

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#80]
## Feature Request

We need map view to show actions with recipients and possibly distribution centre

**Comment by machi1990** [comment]
> We need map view to show actions with recipients and possibly distribution centre

I am wondering whether we should link the distribution center marker and recipient marker with a polyline?

**Comment by wtrocki** [comment]
@machi1990 Not at the moment. You can use route APi to calculate routes on click but that is really stretch goal

**Comment by machi1990** [comment]
Okay, I'd just display distribution centers and recipient as marker of separate colours to differentiate them a little.
