### ISSUE TITLE
Invalid forms declaration - replacing volunteers selection with search component

### ISSUE THREAD

**Issue by wtrocki** [aerogear/OpenVolunteerPlatform#86]
https://github.com/aerogear/OpenVolunteerPlatform/blob/bdab69b6fd9f95fb4356ed9622697f92a635d1b4/platform/client-admin/src/forms/createVolunteerAction.ts#L25

**Comment by machi1990** [comment]
Is this a bug?

**Comment by wtrocki** [comment]
Possible improvement, but I think this is very low priority right now. I will leave it l.
